import React from "react";
import "./About.css";

const About = () => {
    return <div className="about-container">
        <h3 className="heading-about">What is Cybercell?</h3>
        <div className="about-box">
            <p className="club-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam, perspiciatis qui praesentium a quasi aut nobis repudiandae quas esse corporis laborum. Labore, facilis ad corporis eveniet unde quidem iste deleniti. Sit magni aspernatur eveniet accusamus in ducimus expedita, architecto harum esse placeat dicta cum ipsum ut rem doloremque. Voluptatibus quos optio vitae, repudiandae eveniet, repellendus iste facilis repellat non possimus autem dicta tempore sunt? Dolorem laboriosam esse iusto enim obcaecati, veritatis ipsa sunt velit explicabo doloribus distinctio et quibusdam eius error optio tempora ullam. Debitis, accusamus. Unde sunt praesentium dignissimos expedita esse temporibus dolore quasi amet ipsa. Possimus minus nemo neque minima quae ipsam, soluta eos quidem odio hic ab, fugiat nostrum cum earum eligendi accusamus facilis laborum vero quam nam recusandae magnam. Totam explicabo fugiat eaque quis minima alias ipsam ut, ea voluptate illo ducimus voluptatibus quo quia amet, esse incidunt? Asperiores, omnis sed sint quidem ab ipsam quis tempore enim cum blanditiis. Beatae explicabo temporibus pariatur minima velit praesentium, ducimus dicta consectetur debitis iusto veniam optio. Dolorem dolores architecto at, esse hic aperiam quaerat eos modi beatae aspernatur molestias nihil non dolorum quisquam, accusamus doloribus. Voluptatem consequuntur praesentium ad at saepe minima architecto quae voluptatum id qui repellat nostrum repellendus commodi ut sed impedit, minus officiis labore modi exercitationem? Architecto ab eum illo, exercitationem iste quia perferendis nobis in ipsum dolorem, rem odio provident, nulla quidem aliquam eius ea consequuntur. Dolore adipisci voluptatum iste ad inventore. Corporis quis quas architecto eum numquam, cum blanditiis beatae, esse unde accusamus reiciendis aperiam sint, qui praesentium illum. Facilis cum molestias ullam adipisci molestiae voluptatibus sint doloremque aliquid quaerat velit provident officiis vel facere aut unde, ipsa illum voluptatem, alias ea voluptas aspernatur. Voluptas, adipisci mollitia iusto ducimus nihil, labore neque cum eaque quo voluptatum vel iste modi repellat sed perspiciatis dolor?</p>
            <div>
                <p className="heading-about text-center">Our Slogan</p>
            <p className="club-slogan">We make people who secure our future.</p>
            </div>
            <div className="about-dept">
                <h3 className="dept-heading">Technical</h3>
                <p className="dept-desc">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis assumenda veniam culpa, neque cupiditate voluptatibus iste aut ipsa. Maiores, magni sapiente ut ipsum et veniam veritatis. Atque in, numquam ratione quaerat veritatis eius deleniti dolore delectus praesentium ipsa totam perferendis, non neque eum tempora earum tenetur doloremque quam, eos maxime sint! A id quisquam dolor laboriosam officiis vitae, at deleniti numquam. Sunt error culpa a similique beatae temporibus qui nobis quod est? Facilis recusandae dolore, unde beatae nostrum cumque, a velit earum sunt corporis ex libero molestiae, deserunt deleniti nesciunt eligendi nemo fugiat officiis ea id ad reiciendis! Enim culpa illo qui nisi id ut assumenda quam perspiciatis vero illum nobis, ipsum explicabo, eius et, omnis veritatis eveniet eligendi error?</p>
                <h3 className="dept-heading">Developer Team</h3>
                <p className="dept-desc">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis assumenda veniam culpa, neque cupiditate voluptatibus iste aut ipsa. Maiores, magni sapiente ut ipsum et veniam veritatis. Atque in, numquam ratione quaerat veritatis eius deleniti dolore delectus praesentium ipsa totam perferendis, non neque eum tempora earum tenetur doloremque quam, eos maxime sint! A id quisquam dolor laboriosam officiis vitae, at deleniti numquam. Sunt error culpa a similique beatae temporibus qui nobis quod est? Facilis recusandae dolore, unde beatae nostrum cumque, a velit earum sunt corporis ex libero molestiae, deserunt deleniti nesciunt eligendi nemo fugiat officiis ea id ad reiciendis! Enim culpa illo qui nisi id ut assumenda quam perspiciatis vero illum nobis, ipsum explicabo, eius et, omnis veritatis eveniet eligendi error?</p>
                <h3 className="dept-heading">HR Team</h3>
                <p className="dept-desc">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis assumenda veniam culpa, neque cupiditate voluptatibus iste aut ipsa. Maiores, magni sapiente ut ipsum et veniam veritatis. Atque in, numquam ratione quaerat veritatis eius deleniti dolore delectus praesentium ipsa totam perferendis, non neque eum tempora earum tenetur doloremque quam, eos maxime sint! A id quisquam dolor laboriosam officiis vitae, at deleniti numquam. Sunt error culpa a similique beatae temporibus qui nobis quod est? Facilis recusandae dolore, unde beatae nostrum cumque, a velit earum sunt corporis ex libero molestiae, deserunt deleniti nesciunt eligendi nemo fugiat officiis ea id ad reiciendis! Enim culpa illo qui nisi id ut assumenda quam perspiciatis vero illum nobis, ipsum explicabo, eius et, omnis veritatis eveniet eligendi error?</p>
            </div>
            <div className="club-benfits">
                <h3 id="club-benefits" className="heading-about">
                    What Cybercell Provide?
                </h3>
                <p className="benefits-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. At provident dignissimos eos odio, facilis ducimus doloremque corrupti molestiae similique repellat! Dolor enim autem corrupti, quod ea impedit dicta placeat repellendus dolore cum assumenda voluptatem suscipit, magnam perferendis voluptas qui asperiores quas adipisci neque repudiandae atque quae. Maiores doloremque consequatur non fuga ex ullam praesentium at ut, adipisci magni provident, dolorum unde perspiciatis reiciendis officia. Aliquam iure veniam esse, velit ducimus cumque sed quia pariatur itaque, at facilis incidunt distinctio maxime unde, cum a fugit deleniti! Eius, deleniti omnis similique dicta modi unde harum commodi illum itaque dignissimos in tempore aut nemo cupiditate aperiam quibusdam ratione. Tenetur, debitis dolor sint voluptas mollitia minima obcaecati molestias molestiae totam a suscipit esse velit.</p>
            </div>
        </div>
    </div>
}
export default About;